In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
numpy_array = np.array(lista)
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
numpy_array[1]

2

In [11]:
numpy_array[0] + numpy_array[5]

7

In [15]:
matriz[0,2]

3

In [19]:
numpy_array[:3]

array([1, 2, 3])

In [20]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [22]:
matriz_3 = [[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]]
array_3 = np.array(matriz_3)
array_3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])