In [3]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [10]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [16]:
arr2.astype(np.float64)

array([1., 2., 3., 4.])

In [17]:
arr = np.arange(0,10)
arr.astype(np.bool_)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [21]:
arr = np.arange(0,10)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

In [22]:
arr.astype(np.int8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)