In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:
tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


3

# Agregar o eliminar dimensiones

In [13]:
vector = np.array([1,2,3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [19]:
print(np.expand_dims(np.array([1,2,3]), axis=0))
print(np.expand_dims(np.array([1,2,3]), axis=1))

[[1 2 3]]
[[1]
 [2]
 [3]]


In [21]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
