In [2]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(4)
np.random.rand(4,4)
np.random.randint(1, 100, (10,10))

array([[27, 49,  6, 87, 74, 27,  1, 67, 34, 38],
       [ 1, 83,  7, 24, 43, 14, 95, 91, 25, 11],
       [25, 98, 93, 91, 56, 49, 42, 23, 11, 10],
       [14, 55, 64, 62, 82, 79, 45, 10, 76, 14],
       [15,  6, 23, 83, 73, 69,  3, 49,  5, 35],
       [24, 89, 20, 26, 51, 17, 81, 10, 73, 78],
       [68, 98, 64, 74, 85, 18, 38, 75, 70, 64],
       [19, 63, 63, 27, 87, 68, 44, 17, 83, 56],
       [92,  9, 81, 58, 28, 60, 44, 65, 36, 95],
       [63, 33, 10, 62, 46, 46, 10,  5, 69, 49]])